BEGIN;

DROP DOMAIN fk_id15_t;
DROP DOMAIN fk_id31_t;
DROP DOMAIN fk_id63_t;

DROP DOMAIN id15_t;
DROP DOMAIN id31_t;
DROP DOMAIN id63_t;

DROP DOMAIN bool_t;
DROP DOMAIN blittable_t;
DROP DOMAIN ch_t;
DROP DOMAIN ne_str_t;
DROP DOMAIN ipv4_t;
DROP DOMAIN ipv6_t;

DROP DOMAIN i1_t;
DROP DOMAIN i2_t;
DROP DOMAIN i3_t;
DROP DOMAIN i4_t;
DROP DOMAIN i5_t;
DROP DOMAIN i6_t;
DROP DOMAIN i7_t;
DROP DOMAIN i8_t;

DROP DOMAIN i16_t;
DROP DOMAIN i24_t;
DROP DOMAIN i32_t;
DROP DOMAIN i64_t;

DROP DOMAIN u1_t;
DROP DOMAIN u2_t;
DROP DOMAIN u3_t;
DROP DOMAIN u4_t;
DROP DOMAIN u5_t;
DROP DOMAIN u6_t;
DROP DOMAIN u7_t;
DROP DOMAIN u8_t;

DROP DOMAIN u16_t;
DROP DOMAIN u24_t;
DROP DOMAIN u32_t;
DROP DOMAIN u63_t;

DROP DOMAIN direction_t;

DROP TYPE directions_enum_t;

COMMIT;